const deptdata = [
    {
    "DeptCode": "CEO",
    "DeptName": "대표이사",
    "ParentDept": "",
    "DeptLocation": "현대지식산업센터 505호",
    "DeptHead": "양나은",
    "DeptCnt": 10,
    },
    {
        "DeptCode": "TEST",
        "DeptName": "TEST01",
        "ParentDept": "",
        "DeptLocation": "현대지식산업센터 505호",
        "DeptHead": "양나은",
        "DeptCnt": 10,
    },
    {
        "DeptCode": "LGC",
        "DeptName": "물류",
        "ParentDept": "대표이사",
        "DeptLocation": "현대지식산업센터 505호",
        "DeptHead": "양양양",
        "DeptCnt": 8,
    },
    {
        "DeptCode": "MST",
        "DeptName": "경영지원부",
        "ParentDept": "대표이사",
        "DeptLocation": "현대지식산업센터 505호",
        "DeptHead": "이야",
        "DeptCnt": 7,
    },
    {
        "DeptCode": "P1T",
        "DeptName": "압출1팀",
        "ParentDept": "대표이사",
        "DeptLocation": "현대지식산업센터 505호",
        "DeptHead": "후우",
        "DeptCnt": 6,
    },
    {
        "DeptCode": "P2T",
        "DeptName": "압출2팀",
        "ParentDept": "대표이사",
        "DeptLocation": "현대지식산업센터 505호",
        "DeptHead": "STELLA",
        "DeptCnt": 5,
    },
    {
        "DeptCode": "PRT",
        "DeptName": "가공부",
        "ParentDept": "대표이사",
        "DeptLocation": "현대지식산업센터 505호",
        "DeptHead": "ALLEN",
        "DeptCnt": 10,
    },
    {
        "DeptCode": "QCT",
        "DeptName": "품질관리",
        "ParentDept": "대표이사",
        "DeptLocation": "현대지식산업센터 505호",
        "DeptHead": "JANE",
        "DeptCnt": 10,
    },
    {
        "DeptCode": "SMT",
        "DeptName": "영업관리",
        "ParentDept": "대표이사",
        "DeptLocation": "현대지식산업센터 505호",
        "DeptHead": "MERRY",
        "DeptCnt": 10,
    },
    {
        "DeptCode": "ABC",
        "DeptName": "법무팀",
        "ParentDept": "대표이사",
        "DeptLocation": "현대지식산업센터 505호",
        "DeptHead": "HOHO",
        "DeptCnt": 10,
    },
    {
        "DeptCode": "DEF",
        "DeptName": "총무팀",
        "ParentDept": "대표이사",
        "DeptLocation": "현대지식산업센터 505호",
        "DeptHead": "HAHA",
        "DeptCnt": 10,
    },
    {
        "DeptCode": "GHI",
        "DeptName": "인사팀",
        "ParentDept": "대표이사",
        "DeptLocation": "현대지식산업센터 505호",
        "DeptHead": "ADELE",
        "DeptCnt": 10,
    },
    {
        "DeptCode": "JKL",
        "DeptName": "비서실",
        "ParentDept": "대표이사",
        "DeptLocation": "현대지식산업센터 505호",
        "DeptHead": "YOYO",
        "DeptCnt": 10,
    },
    {
        "DeptCode": "ERT",
        "DeptName": "휴게실",
        "ParentDept": "대표이사",
        "DeptLocation": "현대지식산업센터 505호",
        "DeptHead": "ALROHA",
        "DeptCnt": 10,
    },
    {
        "DeptCode": "NNN",
        "DeptName": "관리팀",
        "ParentDept": "대표이사",
        "DeptLocation": "현대지식산업센터 505호",
        "DeptHead": "CHCH",
        "DeptCnt": 10,
    },

]

export default deptdata;